spring:
  application:
    name: config-client
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dengshucai/study.git
          search-paths:
            - springcloud-config
      label: master
